### ISSUE TITLE
Cannot find module 'preboot'

### ISSUE THREAD

**Issue by Hongbo-Miao** [angular/universal-starter#142]
It works well before updating preboot, after updating preboot to v4.3.0, got error:

> module.js:442
>     throw err;
>     ^
> 
> Error: Cannot find module 'preboot'
>     at Function.Module._resolveFilename (module.js:440:15)
>     at Function.Module._load (module.js:388:25)
>     at Module.require (module.js:468:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/xxx/universal-starter/node_modules/angular2-universal/dist/node/ng_preboot.js:3:16)
>     at Module._compile (module.js:541:32)
>     at Object.Module._extensions..js (module.js:550:10)
>     at Module.load (module.js:458:32)
>     at tryModuleLoad (module.js:417:12)
>     at Function.Module._load (module.js:409:3)
> [nodemon] app crashed - waiting for file changes before starting...

**Comment by MarkPieszak** [comment]
@jeffwhelpley any idea ?

**Comment by manekinekko** [comment]
@Hongbo-Miao 
1. try installing it manually `npm i preboot` and tell us if this fixes the issue...
2. BTW, are you using Windows ?

**Comment by Hongbo-Miao** [comment]
@manekinekko all packages can be updated only this one cannot.
After doing this, still same error.
```
npm uninstall preboot --save
npm install preboot --save
```
preboot works well on v2.1.2, but not v4.3.0

I am using Mac.

**Comment by MarkPieszak** [comment]
It looks like 4.3 isn't rendering itself correctly, some files aren't being published. The .d.ts file is there, but it's referencing nothing.

**Comment by gdi2290** [comment]
this should be fixed now as we're using latest preboot
